newproject/newproject/newapp/urls.py
from django.urls import path
from . import views

app_name='newapp'
urlpatterns = [

    path('home',views.home,name='home'),
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('new', views.new, name='new'),
    path('form', views.form, name='form'),
    path('logout', views.logout, name='logout'),


]

newproject/newproject/newproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newapp.urls'))
]

newproject/newproject/newapp/models.py
from django.db import models

# Create your models here.
class Banking(models.Model):
    name = models.CharField(max_length=250)
    dob = models.DateField()
    age = models.IntegerField()
    gender = models.CharField(max_length=10, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')])
    phoneno = models.CharField(max_length=15)
    mailid = models.EmailField()
    address = models.TextField()
    district = models.CharField(max_length=100)
    branch = models.CharField(max_length=100)
    # Use a choice field for accounttype and materials
    accounttype = models.CharField(max_length=20, choices=[('S', 'Savings'), ('C', 'Current'), ('F', 'Fixed')])
    materials = models.CharField(max_length=50,
                                 choices=[('D', 'Debit card'), ('C', 'Credit card'), ('P', 'Cheque book')])

newproject/newproject/newapp/views.py
from django.contrib import auth, messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.http import request
from django.shortcuts import render, redirect
from . models import Banking
# Create your views here.
def home(request):
    return render(request,"home.html")


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        cpassword = request.POST['password1']

        if username == '' or password == '':
            messages.add_message(request, messages.INFO, "Username and password are required fields")
            return redirect('/register')

        elif password != cpassword:
            messages.add_message(request, messages.INFO, "Passwords do not match")
            return redirect('/register')

        elif User.objects.filter(username=username).exists():
            messages.add_message(request, messages.INFO, "Username Taken")
            return redirect('/register')

        else:
            user = User.objects.create_user(username=username, password=password)
            user.save()
            print("User created")
            return redirect('/login')

    return render(request, "register.html")

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('/login')
        else:
            messages.info(request,'invalid credentials')
            return redirect('login')

    return render(request,"login.html")




def new(request):
    return render(request,"new.html")


def form(request):
    if request.method == 'POST':
        if request.POST.get('name') and request.POST.get('dob'):
            banking=Banking()
            banking.name = request.POST['name']
            banking.dob = request.POST['dob']
            banking.age = request.POST['age']
            banking.gender = request.POST['gender']
            banking.phoneno = request.POST['phoneno']
            banking.mailid = request.POST['mailid']
            banking.address = request.POST['address']
            banking.district = request.POST['district']
            banking.branch = request.POST['branch']
            banking.accounttype = request.POST['accounttype']
            banking.materials = request.POST['materials']
            banking.save()
            return render(request,"form.html")
        else:
            return render(request,"form.html")
    return render(request,"form.html")


def new(request):
    return render(request,"new.html")
def logout(request):

    auth.logout(request)
    return redirect('/home')

newproject/newproject/templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register Form</title>
     <!--<link rel="stylesheet" href="{% static 'style.css' %}">-->
    <style>

        body
        {
        background-color:#2e8b57;
        }

    </style>
<script>

        var branches = {
        "Thiruvananthapuram": ["Attingal", "Pothencode", "Kattakkada","Varkala"],
        "Pathanamthitta": ["Thiruvalla", "Adoor", "Pandalam","Konni"],
        "Malappuram": ["Nilambur", "Perinthalmanna", "Edakkara","Kottakkal"],
        "Ernakulam": ["Kochi", "Angamaly", "Thrippunithura","Kalamasseri"],
        "Palakkad": ["Pattambi", "Ottappalam", "Mannarkad","Shornur"]
        };


        function updateBranches() {

        var district = document.getElementById("district");
        var branch = document.getElementById("branch");

        branch.innerHTML = "";
        var selectedDistrict = district.value;

        var options = branches[selectedDistrict];

        for (var i = 0; i < options.length; i++) {
        var option = document.createElement("option");
        option.value = options[i];
        option.text = options[i];
        branch.appendChild(option);
        }
        }



function showPopup() {

document.write("Your application was submitted");
document.write("<a href='{% url "newapp:home"  %}'>This is a link</a>");

}

</script>
</head>
<body>

{% if messages %}
    <ul class="messages">
    {% for message in messages %}
      {% if message.tags %}
          <li class="{{ message.tags }}">{{ message }}</li>
      {% else %}
          <li>{{ message }}</li>
      {% endif %}
    {% endfor %}
    </ul>
{% endif %}



<h3><center>Application Form</center></h3>
  <br>
<form action="#" method="POST" >
        {% csrf_token %}
       <input type ="text" name="name" placeholder="enter your name"><br>
       <input type ="date" name="dob" placeholder="enter date of birth"><br>
       <input type ="number" name="age" placeholder="enter your age"><br>
       <input type ="radio" name="gender">Male<br>
       <input type ="radio" name="gender">Female<br>
      <input type ="tel" name="phoneno" placeholder="Phone number"><br>
        <input type ="email" name="mailid" placeholder="Email"><br>
        <input type ="text" name="address" placeholder="enter your address"><br><br>
      District:
            <select id="district" name="district" onchange="updateBranches()">
            <option value="">Select district</option>
                <option value="Thiruvananthapuram">Thiruvananthapuram</option>
                <option value="Pathanamthitta">Pathanamthitta</option>
            <option value="Malappuram">Malappuram</option>
            <option value="Ernakulam">Ernakulam</option>
            <option value="Palakkad">Palakkad</option>
            </select>
            <br><br>
            Branch:
            <select id="branch" name="branch">
            <option value="">Select branch</option>
            </select>
            <br>
            <br>

       Account type<br>
      <input type="checkbox" name="accounttype">Savings account</br>
      <input type="checkbox" name="accounttype">Current account</br>
      <input type="checkbox" name="accounttype">Fixed deposit</br><br>
       Materials provide<br>
      <input type="checkbox" name="materials">Debit card</br>
      <input type="checkbox" name="materials">Credit card</br>
      <input type="checkbox" name="materials">Cheque book</br><br>

<input type="submit" value="Submit" >
<!--<input type="submit" value="Submit">-->
    <a href="{% url 'newapp:logout' %}">Logout</a>



  </form>
</body>
</html>

newproject/newproject/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
<style>
    body
    {
    background-color:#DFD3E3
    }
</style>
</head>
<body>
<nav class="navbar navbar-light bg-dark">
  <a class="navbar-brand" href="" >
      <h5 style="color:white;">Banko</h5>
  </a>
    <div class="dropdown">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
    Branches
  </a>

  <div class="dropdown-menu">
    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvananthapuram">Thiruvananthapuram</a>
    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Pathanamthitta_district">Pathanamthitta</a>
    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Malappuram_district">Malappuram</a>
      <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernakulam">Ernakulam</a>
      <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Palakkad">Paklakkad</a>
  </div>
</div>

    <a href="{% url 'newapp:login'  %}" class="btn btn-success ">Login</a>
    <a href="{% url 'newapp:register'  %}" class="btn btn-success ">Register</a>

</nav>

{% block body %}
{% endblock %}


</body>
</html>

newproject/newproject/templates/login.html
{% extends 'home.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>



  <style>
body {font-family: Arial, Helvetica, sans-serif;}
form {border: 3px solid #f1f1f1;}

input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

button {
  background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

button:hover {
  opacity: 0.8;
}

.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: #f44336;
}


img.avatar {
  width: 40%;
  border-radius: 50%;
}

.container {
  padding: 16px;
}

span.psw {
  float: right;
  padding-top: 16px;
}


@media screen and (max-width: 300px) {
  span.psw {
     display: block;
     float: none;
  }
  .cancelbtn {
     width: 100%;
  }
}
</style>
<script>

function myfun() {
alert("Check your password");
}
</script>

</head>





<body>
 {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                {% if message.tags %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% else %}
                    <li>{{ message }}</li>
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}

    <form action="{% url 'newapp:new'  %}"  method="post">

        {% csrf_token %}

        <!--<input type="text" name="username" placeholder="enter your username"><br>
        <input type="password" name="password" placeholder="password"><br>
        <input type="submit">
    </form>-->



  <div class="container">
    <label for="uname"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="username" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" required>

    <button type="submit">Login</button>
    <label>
      <input type="checkbox" checked="checked" name="remember"> Remember me
    </label>
  </div>

  <div class="container" style="background-color:#f1f1f1">
    <button type="button" class="cancelbtn">Cancel</button>
      <span class="psw">Forgot <a href="javascript:void(0)" onclick="myfun()">password?</a></span>

  </div>
</form>


</body>
</html>

{% endblock %}

newproject/newproject/templates/new.html
{% extends 'home.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

   <a href="{% url 'newapp:form'  %}" class="btn btn-primary ">Registration Form</a>
</body>
</html>
{% endblock %}

newproject/newproject/templates/register.html
{% extends 'home.html' %}
{% block body %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
      <h3></i>Register</h3>



    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                {% if message.tags %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% else %}
                    <li>{{ message }}</li>
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}



    <form action="{% url 'newapp:register'  %}" method="post">
        {% csrf_token %}
         <input type ="text" name="username" placeholder="username"><br>
         <input type ="password" name="password" placeholder="enter your password"><br>
         <input type ="password" name="password1" placeholder="confirm your password"><br>
         <input type="submit">
    </form>





</body>
</html>
<style type="text/css">
.messages {
  list-style-type: none;
  padding: 10px;
}

.error {
  color: red;
}

.info {
  color: blue;
}
</style>

{% endblock %}